#!/usr/bin/env bash
# This script changes the config without killing the worker processes
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
sudo service nginx restart
pkill -o nginx
